### ISSUE TITLE
ksoftiqrd居高不下

### ISSUE THREAD

**Issue by rheatin** [sbwml/builder#3]
本来我是用的你的配置修改了一下内容，workflow编译的，但是装好了发现，连接openwrt的ssh很卡，然后发现负载居高不下，我这个可是i7-6700诶，看了下top是ksoftiqrd4个cpu都是100%，调整半天没搞定，以为自己搞坏了配置，就从你今天最新的release里下了x86的包，结果安装好了，什么都没有动，发现，ksoftiqrd还是隔几秒就占到100%
![image](https://github.com/sbwml/builder/assets/20568588/6c5fd460-a557-43c7-b96c-8bfcc265c0ad)

**Comment by sbwml** [comment]
你把“全锥型 NAT” 关掉观察下看看？

**Comment by rheatin** [comment]
关了确实好了，再开fullcone还是会占用满，fullcone对我来说还是比较重要的，怎么办呢

**Comment by sbwml** [comment]
你可以看一下在 打开fullcone 并且出现 ksoftiqrd 线程负载很高的情况下，OpenWrt LuCI 首页显示的 “活动连接” 数量是多少吗？
